#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: "Sunset的简历"
url: 'https://www.lwd-temp.top'
description: 一个暂时还没有内容的个人简历

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

# description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-101007282-5

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
